version: '3.8'

services:
  backend:
    build:
      context: ./DRDO-backend-main
    container_name: drdo-backend
    ports:
      - "5000:5000"
    env_file:
      - ./DRDO-backend-main/.env
    restart: always

  frontend:
    build:
      context: ./DRDO-Frontend
    container_name: drdo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
