name: Build & Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/drdo-backend ./DRDO-backend-main
        docker push ${{ secrets.DOCKER_USERNAME }}/drdo-backend

    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/drdo-frontend ./DRDO-Frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/drdo-frontend
